# Generated by Django 5.2.10 on 2026-01-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
